persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
log_timestamp true

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous true

max_connections -1

max_inflight_messages 1000
max_queued_messages 10000

sys_interval 10
autosave_interval 300

retain_available true
message_size_limit 10485760

listener 1884
protocol mqtt
allow_anonymous false
password_file /mosquitto/config/passwd
