INFLUXDB_URL = "http://localhost:8086"
INFLUXDB_TOKEN = "my-token"
INFLUXDB_ORG = "transport-history"
INFLUXDB_BUCKET = "chariot-sensors"

MQTT_BROKER = "localhost"
MQTT_PORT = 1883
MQTT_TOPIC_ALERT = "chariot/alerts"
MQTT_TOPIC_DATA = "chariot/data"

FASTAPI_HOST = "0.0.0.0"
FASTAPI_PORT = 8000

ALERT_ROLL_ANGLE_THRESHOLD = 20.0
ALERT_SLIP_RATE_LOW = 0.05
ALERT_SLIP_RATE_HIGH = 0.8

CHARIOT_WHEELBASE = 2.5
CHARIOT_TRACK_WIDTH = 1.8
CHARIOT_CG_HEIGHT = 0.8
CHARIOT_ROLL_CENTER_HEIGHT = 0.3
